### ISSUE TITLE
useSSL=false not working?!

### ISSUE THREAD

**Issue by uschtwill** [junegunn/jdbc-helper#3]
Hey, I know you haven't updated this gem in years, but I decided to give it a shot anyways. :)

So far, everything is working fine, only that I am trying to suppress

`Fri Mar 31 14:50:25 UTC 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit optionisn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.`

by providing `useSSL=false` like so:

```
mysql = JDBCHelper::MySQL.connect("host", "username", "password", "database",
                                  useSSL: false)
```

...which unfortunately is not working. Why not? What am I not getting?

**Comment by junegunn** [comment]
You're right that this gem is no longer maintained, but as this is a bug that can be easily fixed, I just pushed a new version of the gem. Please try 0.8.3 and see if it helps.

**Comment by uschtwill** [comment]
Works like a charm! Thank you!
